# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ConfirmDestroySession.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ConfirmDestroySession.proto',
  package='MAPAPI.Response2',
  syntax='proto2',
  serialized_pb=_b('\n\x1b\x43onfirmDestroySession.proto\x12\x10MAPAPI.Response2\">\n\x15\x43onfirmDestroySession\x12\x0f\n\x07MapName\x18\x01 \x01(\t\x12\x14\n\tUserCount\x18\x02 \x01(\x05:\x01\x30')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CONFIRMDESTROYSESSION = _descriptor.Descriptor(
  name='ConfirmDestroySession',
  full_name='MAPAPI.Response2.ConfirmDestroySession',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MapName', full_name='MAPAPI.Response2.ConfirmDestroySession.MapName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='UserCount', full_name='MAPAPI.Response2.ConfirmDestroySession.UserCount', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=111,
)

DESCRIPTOR.message_types_by_name['ConfirmDestroySession'] = _CONFIRMDESTROYSESSION

ConfirmDestroySession = _reflection.GeneratedProtocolMessageType('ConfirmDestroySession', (_message.Message,), dict(
  DESCRIPTOR = _CONFIRMDESTROYSESSION,
  __module__ = 'ConfirmDestroySession_pb2'
  # @@protoc_insertion_point(class_scope:MAPAPI.Response2.ConfirmDestroySession)
  ))
_sym_db.RegisterMessage(ConfirmDestroySession)


# @@protoc_insertion_point(module_scope)
