# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HeightTilesStruct.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='HeightTilesStruct.proto',
  package='MAPAPI.Response13',
  syntax='proto2',
  serialized_pb=_b('\n\x17HeightTilesStruct.proto\x12\x11MAPAPI.Response13\"@\n\x11HeightTilesStruct\x12+\n\x05\x42lock\x18\x01 \x03(\x0b\x32\x1c.MAPAPI.Response13.wallTypes\"A\n\twallTypes\x12\x10\n\x05Side0\x18\x01 \x01(\x05:\x01\x30\x12\x10\n\x05Side1\x18\x02 \x01(\x05:\x01\x30\x12\x10\n\x05Side2\x18\x03 \x01(\x05:\x01\x30')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HEIGHTTILESSTRUCT = _descriptor.Descriptor(
  name='HeightTilesStruct',
  full_name='MAPAPI.Response13.HeightTilesStruct',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Block', full_name='MAPAPI.Response13.HeightTilesStruct.Block', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=110,
)


_WALLTYPES = _descriptor.Descriptor(
  name='wallTypes',
  full_name='MAPAPI.Response13.wallTypes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Side0', full_name='MAPAPI.Response13.wallTypes.Side0', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Side1', full_name='MAPAPI.Response13.wallTypes.Side1', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Side2', full_name='MAPAPI.Response13.wallTypes.Side2', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=177,
)

_HEIGHTTILESSTRUCT.fields_by_name['Block'].message_type = _WALLTYPES
DESCRIPTOR.message_types_by_name['HeightTilesStruct'] = _HEIGHTTILESSTRUCT
DESCRIPTOR.message_types_by_name['wallTypes'] = _WALLTYPES

HeightTilesStruct = _reflection.GeneratedProtocolMessageType('HeightTilesStruct', (_message.Message,), dict(
  DESCRIPTOR = _HEIGHTTILESSTRUCT,
  __module__ = 'HeightTilesStruct_pb2'
  # @@protoc_insertion_point(class_scope:MAPAPI.Response13.HeightTilesStruct)
  ))
_sym_db.RegisterMessage(HeightTilesStruct)

wallTypes = _reflection.GeneratedProtocolMessageType('wallTypes', (_message.Message,), dict(
  DESCRIPTOR = _WALLTYPES,
  __module__ = 'HeightTilesStruct_pb2'
  # @@protoc_insertion_point(class_scope:MAPAPI.Response13.wallTypes)
  ))
_sym_db.RegisterMessage(wallTypes)


# @@protoc_insertion_point(module_scope)
