# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: maps/response/MapList.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='maps/response/MapList.proto',
  package='MAPAPI.Response1318159048',
  syntax='proto2',
  serialized_pb=_b('\n\x1bmaps/response/MapList.proto\x12\x19MAPAPI.Response1318159048\"\x1b\n\x07MapList\x12\x10\n\x08MapNames\x18\x01 \x03(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MAPLIST = _descriptor.Descriptor(
  name='MapList',
  full_name='MAPAPI.Response1318159048.MapList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MapNames', full_name='MAPAPI.Response1318159048.MapList.MapNames', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['MapList'] = _MAPLIST

MapList = _reflection.GeneratedProtocolMessageType('MapList', (_message.Message,), dict(
  DESCRIPTOR = _MAPLIST,
  __module__ = 'maps.response.MapList_pb2'
  # @@protoc_insertion_point(class_scope:MAPAPI.Response1318159048.MapList)
  ))
_sym_db.RegisterMessage(MapList)


# @@protoc_insertion_point(module_scope)
