# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: maps/response/MoveNPC.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import bcl_pb2 as bcl__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='maps/response/MoveNPC.proto',
  package='MAPAPI.Response565566055',
  syntax='proto2',
  serialized_pb=_b('\n\x1bmaps/response/MoveNPC.proto\x12\x18MAPAPI.Response565566055\x1a\tbcl.proto\"D\n\x07MoveNPC\x12\x39\n\x06Object\x18\x01 \x01(\x0b\x32).MAPAPI.Response565566055.NPCObjectStruct\"R\n\x0fNPCObjectStruct\x12\x0c\n\x01x\x18\x01 \x01(\x05:\x01\x30\x12\x0c\n\x01y\x18\x02 \x01(\x05:\x01\x30\x12\x0c\n\x01z\x18\x03 \x01(\x05:\x01\x30\x12\x15\n\x02ID\x18\x04 \x01(\x0b\x32\t.bcl.Guid')
  ,
  dependencies=[bcl__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MOVENPC = _descriptor.Descriptor(
  name='MoveNPC',
  full_name='MAPAPI.Response565566055.MoveNPC',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Object', full_name='MAPAPI.Response565566055.MoveNPC.Object', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=136,
)


_NPCOBJECTSTRUCT = _descriptor.Descriptor(
  name='NPCObjectStruct',
  full_name='MAPAPI.Response565566055.NPCObjectStruct',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='MAPAPI.Response565566055.NPCObjectStruct.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='MAPAPI.Response565566055.NPCObjectStruct.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='MAPAPI.Response565566055.NPCObjectStruct.z', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ID', full_name='MAPAPI.Response565566055.NPCObjectStruct.ID', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=220,
)

_MOVENPC.fields_by_name['Object'].message_type = _NPCOBJECTSTRUCT
_NPCOBJECTSTRUCT.fields_by_name['ID'].message_type = bcl__pb2._GUID
DESCRIPTOR.message_types_by_name['MoveNPC'] = _MOVENPC
DESCRIPTOR.message_types_by_name['NPCObjectStruct'] = _NPCOBJECTSTRUCT

MoveNPC = _reflection.GeneratedProtocolMessageType('MoveNPC', (_message.Message,), dict(
  DESCRIPTOR = _MOVENPC,
  __module__ = 'maps.response.MoveNPC_pb2'
  # @@protoc_insertion_point(class_scope:MAPAPI.Response565566055.MoveNPC)
  ))
_sym_db.RegisterMessage(MoveNPC)

NPCObjectStruct = _reflection.GeneratedProtocolMessageType('NPCObjectStruct', (_message.Message,), dict(
  DESCRIPTOR = _NPCOBJECTSTRUCT,
  __module__ = 'maps.response.MoveNPC_pb2'
  # @@protoc_insertion_point(class_scope:MAPAPI.Response565566055.NPCObjectStruct)
  ))
_sym_db.RegisterMessage(NPCObjectStruct)


# @@protoc_insertion_point(module_scope)
