# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NPCSettingStruct.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='NPCSettingStruct.proto',
  package='MAPAPI.Response28',
  syntax='proto2',
  serialized_pb=_b('\n\x16NPCSettingStruct.proto\x12\x11MAPAPI.Response28\"\xbc\x02\n\x10NPCSettingStruct\x12\x0f\n\x07NPCName\x18\x01 \x01(\t\x12\x0e\n\x06\x46\x61\x63ing\x18\x02 \x01(\t\x12\x13\n\x0bSightAction\x18\x03 \x01(\t\x12\x0e\n\x03LOS\x18\x04 \x01(\x05:\x01\x30\x12\x0c\n\x04Path\x18\x05 \x01(\t\x12\x16\n\x07\x45nabled\x18\x06 \x01(\x08:\x05\x66\x61lse\x12\x17\n\x08WalkFast\x18\x07 \x01(\x08:\x05\x66\x61lse\x12\x1b\n\x0cLookRandomly\x18\x08 \x01(\x08:\x05\x66\x61lse\x12\x11\n\x06Sprite\x18\t \x01(\x05:\x01\x30\x12\x0c\n\x04Tags\x18\n \x01(\t\x12\x0e\n\x06Script\x18\x0b \x01(\t\x12\x12\n\nNameColour\x18\x0c \x01(\t\x12\x13\n\x0bStartScript\x18\r \x01(\t\x12\x12\n\nSpottedSFX\x18\x0e \x01(\t\x12\x18\n\tDontMerge\x18\x0f \x01(\x08:\x05\x66\x61lse')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_NPCSETTINGSTRUCT = _descriptor.Descriptor(
  name='NPCSettingStruct',
  full_name='MAPAPI.Response28.NPCSettingStruct',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='NPCName', full_name='MAPAPI.Response28.NPCSettingStruct.NPCName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Facing', full_name='MAPAPI.Response28.NPCSettingStruct.Facing', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SightAction', full_name='MAPAPI.Response28.NPCSettingStruct.SightAction', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LOS', full_name='MAPAPI.Response28.NPCSettingStruct.LOS', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Path', full_name='MAPAPI.Response28.NPCSettingStruct.Path', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Enabled', full_name='MAPAPI.Response28.NPCSettingStruct.Enabled', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='WalkFast', full_name='MAPAPI.Response28.NPCSettingStruct.WalkFast', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LookRandomly', full_name='MAPAPI.Response28.NPCSettingStruct.LookRandomly', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Sprite', full_name='MAPAPI.Response28.NPCSettingStruct.Sprite', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Tags', full_name='MAPAPI.Response28.NPCSettingStruct.Tags', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Script', full_name='MAPAPI.Response28.NPCSettingStruct.Script', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='NameColour', full_name='MAPAPI.Response28.NPCSettingStruct.NameColour', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='StartScript', full_name='MAPAPI.Response28.NPCSettingStruct.StartScript', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SpottedSFX', full_name='MAPAPI.Response28.NPCSettingStruct.SpottedSFX', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DontMerge', full_name='MAPAPI.Response28.NPCSettingStruct.DontMerge', index=14,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=362,
)

DESCRIPTOR.message_types_by_name['NPCSettingStruct'] = _NPCSETTINGSTRUCT

NPCSettingStruct = _reflection.GeneratedProtocolMessageType('NPCSettingStruct', (_message.Message,), dict(
  DESCRIPTOR = _NPCSETTINGSTRUCT,
  __module__ = 'NPCSettingStruct_pb2'
  # @@protoc_insertion_point(class_scope:MAPAPI.Response28.NPCSettingStruct)
  ))
_sym_db.RegisterMessage(NPCSettingStruct)


# @@protoc_insertion_point(module_scope)
