# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: maps/response/tileInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='maps/response/tileInfo.proto',
  package='MAPAPI.Response1285480207',
  syntax='proto2',
  serialized_pb=_b('\n\x1cmaps/response/tileInfo.proto\x12\x19MAPAPI.Response1285480207\"\x85\x01\n\x08tileInfo\x12\x0f\n\x04PosX\x18\x01 \x01(\x05:\x01\x30\x12\x0f\n\x04PosY\x18\x02 \x01(\x05:\x01\x30\x12\x0f\n\x04Type\x18\x03 \x01(\x05:\x01\x30\x12\x11\n\x06Height\x18\x04 \x01(\x05:\x01\x30\x12\x33\n\x05Sides\x18\x05 \x03(\x0b\x32$.MAPAPI.Response1285480207.wallTypes\"A\n\twallTypes\x12\x10\n\x05Side0\x18\x01 \x01(\x05:\x01\x30\x12\x10\n\x05Side1\x18\x02 \x01(\x05:\x01\x30\x12\x10\n\x05Side2\x18\x03 \x01(\x05:\x01\x30')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TILEINFO = _descriptor.Descriptor(
  name='tileInfo',
  full_name='MAPAPI.Response1285480207.tileInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='PosX', full_name='MAPAPI.Response1285480207.tileInfo.PosX', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PosY', full_name='MAPAPI.Response1285480207.tileInfo.PosY', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Type', full_name='MAPAPI.Response1285480207.tileInfo.Type', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Height', full_name='MAPAPI.Response1285480207.tileInfo.Height', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Sides', full_name='MAPAPI.Response1285480207.tileInfo.Sides', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=193,
)


_WALLTYPES = _descriptor.Descriptor(
  name='wallTypes',
  full_name='MAPAPI.Response1285480207.wallTypes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Side0', full_name='MAPAPI.Response1285480207.wallTypes.Side0', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Side1', full_name='MAPAPI.Response1285480207.wallTypes.Side1', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Side2', full_name='MAPAPI.Response1285480207.wallTypes.Side2', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=260,
)

_TILEINFO.fields_by_name['Sides'].message_type = _WALLTYPES
DESCRIPTOR.message_types_by_name['tileInfo'] = _TILEINFO
DESCRIPTOR.message_types_by_name['wallTypes'] = _WALLTYPES

tileInfo = _reflection.GeneratedProtocolMessageType('tileInfo', (_message.Message,), dict(
  DESCRIPTOR = _TILEINFO,
  __module__ = 'maps.response.tileInfo_pb2'
  # @@protoc_insertion_point(class_scope:MAPAPI.Response1285480207.tileInfo)
  ))
_sym_db.RegisterMessage(tileInfo)

wallTypes = _reflection.GeneratedProtocolMessageType('wallTypes', (_message.Message,), dict(
  DESCRIPTOR = _WALLTYPES,
  __module__ = 'maps.response.tileInfo_pb2'
  # @@protoc_insertion_point(class_scope:MAPAPI.Response1285480207.wallTypes)
  ))
_sym_db.RegisterMessage(wallTypes)


# @@protoc_insertion_point(module_scope)
