# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Effect.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import bcl_pb2 as bcl__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Effect.proto',
  package='PSXAPI.Request17',
  syntax='proto2',
  serialized_pb=_b('\n\x0c\x45\x66\x66\x65\x63t.proto\x12\x10PSXAPI.Request17\x1a\tbcl.proto\"X\n\x06\x45\x66\x66\x65\x63t\x12\x36\n\x06\x41\x63tion\x18\x01 \x01(\x0e\x32\x1e.PSXAPI.Request17.EffectAction:\x06\x43\x61ncel\x12\x16\n\x03UID\x18\x02 \x01(\x0b\x32\t.bcl.Guid*#\n\x0c\x45\x66\x66\x65\x63tAction\x12\n\n\x06\x43\x61ncel\x10\x00\x12\x07\n\x03Use\x10\x01')
  ,
  dependencies=[bcl__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_EFFECTACTION = _descriptor.EnumDescriptor(
  name='EffectAction',
  full_name='PSXAPI.Request17.EffectAction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Cancel', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Use', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=135,
  serialized_end=170,
)
_sym_db.RegisterEnumDescriptor(_EFFECTACTION)

EffectAction = enum_type_wrapper.EnumTypeWrapper(_EFFECTACTION)
Cancel = 0
Use = 1



_EFFECT = _descriptor.Descriptor(
  name='Effect',
  full_name='PSXAPI.Request17.Effect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Action', full_name='PSXAPI.Request17.Effect.Action', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='UID', full_name='PSXAPI.Request17.Effect.UID', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=133,
)

_EFFECT.fields_by_name['Action'].enum_type = _EFFECTACTION
_EFFECT.fields_by_name['UID'].message_type = bcl__pb2._GUID
DESCRIPTOR.message_types_by_name['Effect'] = _EFFECT
DESCRIPTOR.enum_types_by_name['EffectAction'] = _EFFECTACTION

Effect = _reflection.GeneratedProtocolMessageType('Effect', (_message.Message,), dict(
  DESCRIPTOR = _EFFECT,
  __module__ = 'Effect_pb2'
  # @@protoc_insertion_point(class_scope:PSXAPI.Request17.Effect)
  ))
_sym_db.RegisterMessage(Effect)


# @@protoc_insertion_point(module_scope)
