# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game/request/FlyExit.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='game/request/FlyExit.proto',
  package='PSXAPI.Request1198756185',
  syntax='proto2',
  serialized_pb=_b('\n\x1agame/request/FlyExit.proto\x12\x18PSXAPI.Request1198756185\"\x17\n\x07\x46lyExit\x12\x0c\n\x04\x41rea\x18\x01 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FLYEXIT = _descriptor.Descriptor(
  name='FlyExit',
  full_name='PSXAPI.Request1198756185.FlyExit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Area', full_name='PSXAPI.Request1198756185.FlyExit.Area', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=79,
)

DESCRIPTOR.message_types_by_name['FlyExit'] = _FLYEXIT

FlyExit = _reflection.GeneratedProtocolMessageType('FlyExit', (_message.Message,), dict(
  DESCRIPTOR = _FLYEXIT,
  __module__ = 'game.request.FlyExit_pb2'
  # @@protoc_insertion_point(class_scope:PSXAPI.Request1198756185.FlyExit)
  ))
_sym_db.RegisterMessage(FlyExit)


# @@protoc_insertion_point(module_scope)
