# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LobbySwitch.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='LobbySwitch.proto',
  package='PSXAPI.Request38',
  syntax='proto2',
  serialized_pb=_b('\n\x11LobbySwitch.proto\x12\x10PSXAPI.Request38\"\r\n\x0bLobbySwitch')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LOBBYSWITCH = _descriptor.Descriptor(
  name='LobbySwitch',
  full_name='PSXAPI.Request38.LobbySwitch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=52,
)

DESCRIPTOR.message_types_by_name['LobbySwitch'] = _LOBBYSWITCH

LobbySwitch = _reflection.GeneratedProtocolMessageType('LobbySwitch', (_message.Message,), dict(
  DESCRIPTOR = _LOBBYSWITCH,
  __module__ = 'LobbySwitch_pb2'
  # @@protoc_insertion_point(class_scope:PSXAPI.Request38.LobbySwitch)
  ))
_sym_db.RegisterMessage(LobbySwitch)


# @@protoc_insertion_point(module_scope)
