# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LobbyKick.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='LobbyKick.proto',
  package='PSXAPI.Request426618449',
  syntax='proto2',
  serialized_pb=_b('\n\x0fLobbyKick.proto\x12\x17PSXAPI.Request426618449\"\x1d\n\tLobbyKick\x12\x10\n\x08Username\x18\x01 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LOBBYKICK = _descriptor.Descriptor(
  name='LobbyKick',
  full_name='PSXAPI.Request426618449.LobbyKick',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Username', full_name='PSXAPI.Request426618449.LobbyKick.Username', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=73,
)

DESCRIPTOR.message_types_by_name['LobbyKick'] = _LOBBYKICK

LobbyKick = _reflection.GeneratedProtocolMessageType('LobbyKick', (_message.Message,), dict(
  DESCRIPTOR = _LOBBYKICK,
  __module__ = 'LobbyKick_pb2'
  # @@protoc_insertion_point(class_scope:PSXAPI.Request426618449.LobbyKick)
  ))
_sym_db.RegisterMessage(LobbyKick)


# @@protoc_insertion_point(module_scope)
