# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Spin.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Spin.proto',
  package='PSXAPI.Request784181591',
  syntax='proto2',
  serialized_pb=_b('\n\nSpin.proto\x12\x17PSXAPI.Request784181591\"i\n\x04Spin\x12\r\n\x02ID\x18\x01 \x01(\x05:\x01\x30\x12R\n\x03\x42\x65t\x18\x02 \x01(\x0e\x32:.PSXAPI.Request784181591.PREFIX_AGDFASBV2137981436.SpinBet:\tNoneValue\"V\n\x19PREFIX_AGDFASBV2137981436\"9\n\x07SpinBet\x12\r\n\tNoneValue\x10\x00\x12\t\n\x05\x43oin1\x10\x01\x12\t\n\x05\x43oin2\x10\x02\x12\t\n\x05\x43oin3\x10\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PREFIX_AGDFASBV2137981436_SPINBET = _descriptor.EnumDescriptor(
  name='SpinBet',
  full_name='PSXAPI.Request784181591.PREFIX_AGDFASBV2137981436.SpinBet',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NoneValue', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Coin1', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Coin2', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Coin3', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=175,
  serialized_end=232,
)
_sym_db.RegisterEnumDescriptor(_PREFIX_AGDFASBV2137981436_SPINBET)


_SPIN = _descriptor.Descriptor(
  name='Spin',
  full_name='PSXAPI.Request784181591.Spin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='PSXAPI.Request784181591.Spin.ID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Bet', full_name='PSXAPI.Request784181591.Spin.Bet', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=144,
)


_PREFIX_AGDFASBV2137981436 = _descriptor.Descriptor(
  name='PREFIX_AGDFASBV2137981436',
  full_name='PSXAPI.Request784181591.PREFIX_AGDFASBV2137981436',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PREFIX_AGDFASBV2137981436_SPINBET,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=232,
)

_SPIN.fields_by_name['Bet'].enum_type = _PREFIX_AGDFASBV2137981436_SPINBET
_PREFIX_AGDFASBV2137981436_SPINBET.containing_type = _PREFIX_AGDFASBV2137981436
DESCRIPTOR.message_types_by_name['Spin'] = _SPIN
DESCRIPTOR.message_types_by_name['PREFIX_AGDFASBV2137981436'] = _PREFIX_AGDFASBV2137981436

Spin = _reflection.GeneratedProtocolMessageType('Spin', (_message.Message,), dict(
  DESCRIPTOR = _SPIN,
  __module__ = 'Spin_pb2'
  # @@protoc_insertion_point(class_scope:PSXAPI.Request784181591.Spin)
  ))
_sym_db.RegisterMessage(Spin)

PREFIX_AGDFASBV2137981436 = _reflection.GeneratedProtocolMessageType('PREFIX_AGDFASBV2137981436', (_message.Message,), dict(
  DESCRIPTOR = _PREFIX_AGDFASBV2137981436,
  __module__ = 'Spin_pb2'
  # @@protoc_insertion_point(class_scope:PSXAPI.Request784181591.PREFIX_AGDFASBV2137981436)
  ))
_sym_db.RegisterMessage(PREFIX_AGDFASBV2137981436)


# @@protoc_insertion_point(module_scope)
