# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VerifyEmail.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='VerifyEmail.proto',
  package='PSXAPI.Request2109244228',
  syntax='proto2',
  serialized_pb=_b('\n\x11VerifyEmail.proto\x12\x18PSXAPI.Request2109244228\"\x92\x01\n\x0bVerifyEmail\x12`\n\x06\x41\x63tion\x18\x01 \x01(\x0e\x32\x45.PSXAPI.Request2109244228.PREFIX_AGDFASBV1357584046.VerifyEmailAction:\tNoneValue\x12\x10\n\x08Username\x18\x02 \x01(\t\x12\x0f\n\x04\x43ode\x18\x03 \x01(\x05:\x01\x30\"W\n\x19PREFIX_AGDFASBV1357584046\":\n\x11VerifyEmailAction\x12\r\n\tNoneValue\x10\x00\x12\n\n\x06Verify\x10\x01\x12\n\n\x06Resend\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PREFIX_AGDFASBV1357584046_VERIFYEMAILACTION = _descriptor.EnumDescriptor(
  name='VerifyEmailAction',
  full_name='PSXAPI.Request2109244228.PREFIX_AGDFASBV1357584046.VerifyEmailAction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NoneValue', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Verify', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Resend', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=225,
  serialized_end=283,
)
_sym_db.RegisterEnumDescriptor(_PREFIX_AGDFASBV1357584046_VERIFYEMAILACTION)


_VERIFYEMAIL = _descriptor.Descriptor(
  name='VerifyEmail',
  full_name='PSXAPI.Request2109244228.VerifyEmail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Action', full_name='PSXAPI.Request2109244228.VerifyEmail.Action', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Username', full_name='PSXAPI.Request2109244228.VerifyEmail.Username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Code', full_name='PSXAPI.Request2109244228.VerifyEmail.Code', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=194,
)


_PREFIX_AGDFASBV1357584046 = _descriptor.Descriptor(
  name='PREFIX_AGDFASBV1357584046',
  full_name='PSXAPI.Request2109244228.PREFIX_AGDFASBV1357584046',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PREFIX_AGDFASBV1357584046_VERIFYEMAILACTION,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=283,
)

_VERIFYEMAIL.fields_by_name['Action'].enum_type = _PREFIX_AGDFASBV1357584046_VERIFYEMAILACTION
_PREFIX_AGDFASBV1357584046_VERIFYEMAILACTION.containing_type = _PREFIX_AGDFASBV1357584046
DESCRIPTOR.message_types_by_name['VerifyEmail'] = _VERIFYEMAIL
DESCRIPTOR.message_types_by_name['PREFIX_AGDFASBV1357584046'] = _PREFIX_AGDFASBV1357584046

VerifyEmail = _reflection.GeneratedProtocolMessageType('VerifyEmail', (_message.Message,), dict(
  DESCRIPTOR = _VERIFYEMAIL,
  __module__ = 'VerifyEmail_pb2'
  # @@protoc_insertion_point(class_scope:PSXAPI.Request2109244228.VerifyEmail)
  ))
_sym_db.RegisterMessage(VerifyEmail)

PREFIX_AGDFASBV1357584046 = _reflection.GeneratedProtocolMessageType('PREFIX_AGDFASBV1357584046', (_message.Message,), dict(
  DESCRIPTOR = _PREFIX_AGDFASBV1357584046,
  __module__ = 'VerifyEmail_pb2'
  # @@protoc_insertion_point(class_scope:PSXAPI.Request2109244228.PREFIX_AGDFASBV1357584046)
  ))
_sym_db.RegisterMessage(PREFIX_AGDFASBV1357584046)


# @@protoc_insertion_point(module_scope)
