# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game/response/CreateUser.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='game/response/CreateUser.proto',
  package='PSXAPI.Response1893323167',
  syntax='proto2',
  serialized_pb=_b('\n\x1egame/response/CreateUser.proto\x12\x19PSXAPI.Response1893323167\"j\n\nCreateUser\x12\\\n\x06Result\x18\x01 \x01(\x0e\x32\x45.PSXAPI.Response1893323167.PREFIX_AGDFASBV2013162786.CreateUserResult:\x05\x45rror\"G\n\x19PREFIX_AGDFASBV2013162786\"*\n\x10\x43reateUserResult\x12\t\n\x05\x45rror\x10\x00\x12\x0b\n\x07Success\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PREFIX_AGDFASBV2013162786_CREATEUSERRESULT = _descriptor.EnumDescriptor(
  name='CreateUserResult',
  full_name='PSXAPI.Response1893323167.PREFIX_AGDFASBV2013162786.CreateUserResult',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Error', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Success', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=198,
  serialized_end=240,
)
_sym_db.RegisterEnumDescriptor(_PREFIX_AGDFASBV2013162786_CREATEUSERRESULT)


_CREATEUSER = _descriptor.Descriptor(
  name='CreateUser',
  full_name='PSXAPI.Response1893323167.CreateUser',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Result', full_name='PSXAPI.Response1893323167.CreateUser.Result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=167,
)


_PREFIX_AGDFASBV2013162786 = _descriptor.Descriptor(
  name='PREFIX_AGDFASBV2013162786',
  full_name='PSXAPI.Response1893323167.PREFIX_AGDFASBV2013162786',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PREFIX_AGDFASBV2013162786_CREATEUSERRESULT,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=240,
)

_CREATEUSER.fields_by_name['Result'].enum_type = _PREFIX_AGDFASBV2013162786_CREATEUSERRESULT
_PREFIX_AGDFASBV2013162786_CREATEUSERRESULT.containing_type = _PREFIX_AGDFASBV2013162786
DESCRIPTOR.message_types_by_name['CreateUser'] = _CREATEUSER
DESCRIPTOR.message_types_by_name['PREFIX_AGDFASBV2013162786'] = _PREFIX_AGDFASBV2013162786

CreateUser = _reflection.GeneratedProtocolMessageType('CreateUser', (_message.Message,), dict(
  DESCRIPTOR = _CREATEUSER,
  __module__ = 'game.response.CreateUser_pb2'
  # @@protoc_insertion_point(class_scope:PSXAPI.Response1893323167.CreateUser)
  ))
_sym_db.RegisterMessage(CreateUser)

PREFIX_AGDFASBV2013162786 = _reflection.GeneratedProtocolMessageType('PREFIX_AGDFASBV2013162786', (_message.Message,), dict(
  DESCRIPTOR = _PREFIX_AGDFASBV2013162786,
  __module__ = 'game.response.CreateUser_pb2'
  # @@protoc_insertion_point(class_scope:PSXAPI.Response1893323167.PREFIX_AGDFASBV2013162786)
  ))
_sym_db.RegisterMessage(PREFIX_AGDFASBV2013162786)


# @@protoc_insertion_point(module_scope)
