# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Fishing.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Fishing.proto',
  package='PSXAPI.Response26',
  syntax='proto2',
  serialized_pb=_b('\n\rFishing.proto\x12\x11PSXAPI.Response26\"\t\n\x07\x46ishing')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FISHING = _descriptor.Descriptor(
  name='Fishing',
  full_name='PSXAPI.Response26.Fishing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=45,
)

DESCRIPTOR.message_types_by_name['Fishing'] = _FISHING

Fishing = _reflection.GeneratedProtocolMessageType('Fishing', (_message.Message,), dict(
  DESCRIPTOR = _FISHING,
  __module__ = 'Fishing_pb2'
  # @@protoc_insertion_point(class_scope:PSXAPI.Response26.Fishing)
  ))
_sym_db.RegisterMessage(Fishing)


# @@protoc_insertion_point(module_scope)
