# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game/response/Loot.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import bcl_pb2 as bcl__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='game/response/Loot.proto',
  package='PSXAPI.Response910864062',
  syntax='proto2',
  serialized_pb=_b('\n\x18game/response/Loot.proto\x12\x18PSXAPI.Response910864062\x1a\tbcl.proto\"\xa6\x01\n\x04Loot\x12\x30\n\x04Vote\x18\x01 \x01(\x0b\x32\".PSXAPI.Response910864062.LootVote\x12\\\n\x06Result\x18\x02 \x01(\x0e\x32\x42.PSXAPI.Response910864062.PREFIX_AGDFASBV2002746575.LootVoteResult:\x08TimedOut\x12\x0e\n\x06Winner\x18\x03 \x01(\t\"n\n\x08LootVote\x12\x19\n\x06VoteID\x18\x01 \x01(\x0b\x32\t.bcl.Guid\x12\x11\n\x06ItemID\x18\x02 \x01(\x05:\x01\x30\x12\x13\n\x08Quantity\x18\x03 \x01(\r:\x01\x30\x12\x1f\n\x08\x44uration\x18\x04 \x01(\x0b\x32\r.bcl.TimeSpan\"Z\n\x19PREFIX_AGDFASBV2002746575\"=\n\x0eLootVoteResult\x12\x0c\n\x08TimedOut\x10\x00\x12\x07\n\x03Won\x10\x01\x12\x08\n\x04Lost\x10\x02\x12\n\n\x06Passed\x10\x03')
  ,
  dependencies=[bcl__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PREFIX_AGDFASBV2002746575_LOOTVOTERESULT = _descriptor.EnumDescriptor(
  name='LootVoteResult',
  full_name='PSXAPI.Response910864062.PREFIX_AGDFASBV2002746575.LootVoteResult',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TimedOut', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Won', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Lost', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Passed', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=375,
  serialized_end=436,
)
_sym_db.RegisterEnumDescriptor(_PREFIX_AGDFASBV2002746575_LOOTVOTERESULT)


_LOOT = _descriptor.Descriptor(
  name='Loot',
  full_name='PSXAPI.Response910864062.Loot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Vote', full_name='PSXAPI.Response910864062.Loot.Vote', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Result', full_name='PSXAPI.Response910864062.Loot.Result', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Winner', full_name='PSXAPI.Response910864062.Loot.Winner', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=232,
)


_LOOTVOTE = _descriptor.Descriptor(
  name='LootVote',
  full_name='PSXAPI.Response910864062.LootVote',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='VoteID', full_name='PSXAPI.Response910864062.LootVote.VoteID', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ItemID', full_name='PSXAPI.Response910864062.LootVote.ItemID', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Quantity', full_name='PSXAPI.Response910864062.LootVote.Quantity', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Duration', full_name='PSXAPI.Response910864062.LootVote.Duration', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=344,
)


_PREFIX_AGDFASBV2002746575 = _descriptor.Descriptor(
  name='PREFIX_AGDFASBV2002746575',
  full_name='PSXAPI.Response910864062.PREFIX_AGDFASBV2002746575',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PREFIX_AGDFASBV2002746575_LOOTVOTERESULT,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=346,
  serialized_end=436,
)

_LOOT.fields_by_name['Vote'].message_type = _LOOTVOTE
_LOOT.fields_by_name['Result'].enum_type = _PREFIX_AGDFASBV2002746575_LOOTVOTERESULT
_LOOTVOTE.fields_by_name['VoteID'].message_type = bcl__pb2._GUID
_LOOTVOTE.fields_by_name['Duration'].message_type = bcl__pb2._TIMESPAN
_PREFIX_AGDFASBV2002746575_LOOTVOTERESULT.containing_type = _PREFIX_AGDFASBV2002746575
DESCRIPTOR.message_types_by_name['Loot'] = _LOOT
DESCRIPTOR.message_types_by_name['LootVote'] = _LOOTVOTE
DESCRIPTOR.message_types_by_name['PREFIX_AGDFASBV2002746575'] = _PREFIX_AGDFASBV2002746575

Loot = _reflection.GeneratedProtocolMessageType('Loot', (_message.Message,), dict(
  DESCRIPTOR = _LOOT,
  __module__ = 'game.response.Loot_pb2'
  # @@protoc_insertion_point(class_scope:PSXAPI.Response910864062.Loot)
  ))
_sym_db.RegisterMessage(Loot)

LootVote = _reflection.GeneratedProtocolMessageType('LootVote', (_message.Message,), dict(
  DESCRIPTOR = _LOOTVOTE,
  __module__ = 'game.response.Loot_pb2'
  # @@protoc_insertion_point(class_scope:PSXAPI.Response910864062.LootVote)
  ))
_sym_db.RegisterMessage(LootVote)

PREFIX_AGDFASBV2002746575 = _reflection.GeneratedProtocolMessageType('PREFIX_AGDFASBV2002746575', (_message.Message,), dict(
  DESCRIPTOR = _PREFIX_AGDFASBV2002746575,
  __module__ = 'game.response.Loot_pb2'
  # @@protoc_insertion_point(class_scope:PSXAPI.Response910864062.PREFIX_AGDFASBV2002746575)
  ))
_sym_db.RegisterMessage(PREFIX_AGDFASBV2002746575)


# @@protoc_insertion_point(module_scope)
