# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Money.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Money.proto',
  package='PSXAPI.Response1261098714',
  syntax='proto2',
  serialized_pb=_b('\n\x0bMoney.proto\x12\x19PSXAPI.Response1261098714\")\n\x05Money\x12\x0f\n\x04Game\x18\x01 \x01(\r:\x01\x30\x12\x0f\n\x04Gold\x18\x02 \x01(\r:\x01\x30')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MONEY = _descriptor.Descriptor(
  name='Money',
  full_name='PSXAPI.Response1261098714.Money',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Game', full_name='PSXAPI.Response1261098714.Money.Game', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Gold', full_name='PSXAPI.Response1261098714.Money.Gold', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=83,
)

DESCRIPTOR.message_types_by_name['Money'] = _MONEY

Money = _reflection.GeneratedProtocolMessageType('Money', (_message.Message,), dict(
  DESCRIPTOR = _MONEY,
  __module__ = 'Money_pb2'
  # @@protoc_insertion_point(class_scope:PSXAPI.Response1261098714.Money)
  ))
_sym_db.RegisterMessage(Money)


# @@protoc_insertion_point(module_scope)
