# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Move.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import bcl_pb2 as bcl__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Move.proto',
  package='PSXAPI.Response56',
  syntax='proto2',
  serialized_pb=_b('\n\nMove.proto\x12\x11PSXAPI.Response56\x1a\tbcl.proto\"\xcc\x01\n\x04Move\x12\x0b\n\x03Map\x18\x01 \x02(\t\x12\t\n\x01X\x18\x02 \x02(\x05\x12\t\n\x01Y\x18\x03 \x02(\x05\x12\x32\n\x06\x41\x63tion\x18\x04 \x01(\x0e\x32\x1d.PSXAPI.Response56.MoveAction:\x03Set\x12>\n\tDirection\x18\x05 \x01(\x0e\x32\".PSXAPI.Response56.PlayerDirection:\x07\x44\x65\x66\x61ult\x12\x1a\n\x07Scripts\x18\x06 \x03(\x0b\x32\t.bcl.Guid\x12\x11\n\x06Height\x18\x07 \x01(\x05:\x01\x30*@\n\nMoveAction\x12\x07\n\x03Set\x10\x00\x12\x07\n\x03Up0\x10\x01\x12\t\n\x05\x44own0\x10\x02\x12\t\n\x05Left0\x10\x03\x12\n\n\x06Right0\x10\x04*I\n\x0fPlayerDirection\x12\x0b\n\x07\x44\x65\x66\x61ult\x10\x00\x12\x07\n\x03Up1\x10\x01\x12\t\n\x05\x44own1\x10\x02\x12\t\n\x05Left1\x10\x03\x12\n\n\x06Right1\x10\x04')
  ,
  dependencies=[bcl__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_MOVEACTION = _descriptor.EnumDescriptor(
  name='MoveAction',
  full_name='PSXAPI.Response56.MoveAction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Set', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Up0', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Down0', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Left0', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Right0', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=251,
  serialized_end=315,
)
_sym_db.RegisterEnumDescriptor(_MOVEACTION)

MoveAction = enum_type_wrapper.EnumTypeWrapper(_MOVEACTION)
_PLAYERDIRECTION = _descriptor.EnumDescriptor(
  name='PlayerDirection',
  full_name='PSXAPI.Response56.PlayerDirection',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Default', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Up1', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Down1', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Left1', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Right1', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=317,
  serialized_end=390,
)
_sym_db.RegisterEnumDescriptor(_PLAYERDIRECTION)

PlayerDirection = enum_type_wrapper.EnumTypeWrapper(_PLAYERDIRECTION)
Set = 0
Up0 = 1
Down0 = 2
Left0 = 3
Right0 = 4
Default = 0
Up1 = 1
Down1 = 2
Left1 = 3
Right1 = 4



_MOVE = _descriptor.Descriptor(
  name='Move',
  full_name='PSXAPI.Response56.Move',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Map', full_name='PSXAPI.Response56.Move.Map', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='X', full_name='PSXAPI.Response56.Move.X', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Y', full_name='PSXAPI.Response56.Move.Y', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Action', full_name='PSXAPI.Response56.Move.Action', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Direction', full_name='PSXAPI.Response56.Move.Direction', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Scripts', full_name='PSXAPI.Response56.Move.Scripts', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Height', full_name='PSXAPI.Response56.Move.Height', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=249,
)

_MOVE.fields_by_name['Action'].enum_type = _MOVEACTION
_MOVE.fields_by_name['Direction'].enum_type = _PLAYERDIRECTION
_MOVE.fields_by_name['Scripts'].message_type = bcl__pb2._GUID
DESCRIPTOR.message_types_by_name['Move'] = _MOVE
DESCRIPTOR.enum_types_by_name['MoveAction'] = _MOVEACTION
DESCRIPTOR.enum_types_by_name['PlayerDirection'] = _PLAYERDIRECTION

Move = _reflection.GeneratedProtocolMessageType('Move', (_message.Message,), dict(
  DESCRIPTOR = _MOVE,
  __module__ = 'Move_pb2'
  # @@protoc_insertion_point(class_scope:PSXAPI.Response56.Move)
  ))
_sym_db.RegisterMessage(Move)


# @@protoc_insertion_point(module_scope)
