# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Spin.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Spin.proto',
  package='PSXAPI.Response1203978105',
  syntax='proto2',
  serialized_pb=_b('\n\nSpin.proto\x12\x19PSXAPI.Response1203978105\"\xb7\x01\n\x04Spin\x12\r\n\x02ID\x18\x01 \x01(\x05:\x01\x30\x12\x10\n\x05Score\x18\x02 \x01(\x05:\x01\x30\x12\x44\n\x0eWinningSymbols\x18\x03 \x03(\x0b\x32,.PSXAPI.Response1203978105.SpinWinningSymbol\x12\x36\n\x07\x43olumns\x18\x04 \x03(\x0b\x32%.PSXAPI.Response1203978105.SpinColumn\x12\x10\n\x05Total\x18\x05 \x01(\r:\x01\x30\"\x1d\n\nSpinColumn\x12\x0f\n\x07Symbols\x18\x01 \x03(\r\"|\n\x19PREFIX_AGDFASBV1795637361\"_\n\x08SpinMode\x12\x14\n\x10HorizontalCenter\x10\x01\x12\x13\n\x0fHorizontalMulti\x10\x02\x12\x0c\n\x08\x44iagonal\x10\x04\x12\x11\n\rHorizintalAll\x10\x03\x12\x07\n\x03\x41ll\x10\x07\"\xaf\x01\n\x11SpinWinningSymbol\x12P\n\x04Mode\x18\x01 \x01(\x0e\x32=.PSXAPI.Response1203978105.PREFIX_AGDFASBV1795637361.SpinMode:\x03\x41ll\x12\r\n\x02ID\x18\x02 \x01(\r:\x01\x30\x12\x13\n\x08Required\x18\x03 \x01(\x05:\x01\x30\x12\x14\n\tWinPoints\x18\x04 \x01(\x05:\x01\x30\x12\x0e\n\x03Row\x18\x05 \x01(\x05:\x01\x30')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PREFIX_AGDFASBV1795637361_SPINMODE = _descriptor.EnumDescriptor(
  name='SpinMode',
  full_name='PSXAPI.Response1203978105.PREFIX_AGDFASBV1795637361.SpinMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HorizontalCenter', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HorizontalMulti', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Diagonal', index=2, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HorizintalAll', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='All', index=4, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=287,
  serialized_end=382,
)
_sym_db.RegisterEnumDescriptor(_PREFIX_AGDFASBV1795637361_SPINMODE)


_SPIN = _descriptor.Descriptor(
  name='Spin',
  full_name='PSXAPI.Response1203978105.Spin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='PSXAPI.Response1203978105.Spin.ID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Score', full_name='PSXAPI.Response1203978105.Spin.Score', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='WinningSymbols', full_name='PSXAPI.Response1203978105.Spin.WinningSymbols', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Columns', full_name='PSXAPI.Response1203978105.Spin.Columns', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Total', full_name='PSXAPI.Response1203978105.Spin.Total', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=225,
)


_SPINCOLUMN = _descriptor.Descriptor(
  name='SpinColumn',
  full_name='PSXAPI.Response1203978105.SpinColumn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Symbols', full_name='PSXAPI.Response1203978105.SpinColumn.Symbols', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=256,
)


_PREFIX_AGDFASBV1795637361 = _descriptor.Descriptor(
  name='PREFIX_AGDFASBV1795637361',
  full_name='PSXAPI.Response1203978105.PREFIX_AGDFASBV1795637361',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PREFIX_AGDFASBV1795637361_SPINMODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=382,
)


_SPINWINNINGSYMBOL = _descriptor.Descriptor(
  name='SpinWinningSymbol',
  full_name='PSXAPI.Response1203978105.SpinWinningSymbol',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Mode', full_name='PSXAPI.Response1203978105.SpinWinningSymbol.Mode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=7,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ID', full_name='PSXAPI.Response1203978105.SpinWinningSymbol.ID', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Required', full_name='PSXAPI.Response1203978105.SpinWinningSymbol.Required', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='WinPoints', full_name='PSXAPI.Response1203978105.SpinWinningSymbol.WinPoints', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Row', full_name='PSXAPI.Response1203978105.SpinWinningSymbol.Row', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=560,
)

_SPIN.fields_by_name['WinningSymbols'].message_type = _SPINWINNINGSYMBOL
_SPIN.fields_by_name['Columns'].message_type = _SPINCOLUMN
_PREFIX_AGDFASBV1795637361_SPINMODE.containing_type = _PREFIX_AGDFASBV1795637361
_SPINWINNINGSYMBOL.fields_by_name['Mode'].enum_type = _PREFIX_AGDFASBV1795637361_SPINMODE
DESCRIPTOR.message_types_by_name['Spin'] = _SPIN
DESCRIPTOR.message_types_by_name['SpinColumn'] = _SPINCOLUMN
DESCRIPTOR.message_types_by_name['PREFIX_AGDFASBV1795637361'] = _PREFIX_AGDFASBV1795637361
DESCRIPTOR.message_types_by_name['SpinWinningSymbol'] = _SPINWINNINGSYMBOL

Spin = _reflection.GeneratedProtocolMessageType('Spin', (_message.Message,), dict(
  DESCRIPTOR = _SPIN,
  __module__ = 'Spin_pb2'
  # @@protoc_insertion_point(class_scope:PSXAPI.Response1203978105.Spin)
  ))
_sym_db.RegisterMessage(Spin)

SpinColumn = _reflection.GeneratedProtocolMessageType('SpinColumn', (_message.Message,), dict(
  DESCRIPTOR = _SPINCOLUMN,
  __module__ = 'Spin_pb2'
  # @@protoc_insertion_point(class_scope:PSXAPI.Response1203978105.SpinColumn)
  ))
_sym_db.RegisterMessage(SpinColumn)

PREFIX_AGDFASBV1795637361 = _reflection.GeneratedProtocolMessageType('PREFIX_AGDFASBV1795637361', (_message.Message,), dict(
  DESCRIPTOR = _PREFIX_AGDFASBV1795637361,
  __module__ = 'Spin_pb2'
  # @@protoc_insertion_point(class_scope:PSXAPI.Response1203978105.PREFIX_AGDFASBV1795637361)
  ))
_sym_db.RegisterMessage(PREFIX_AGDFASBV1795637361)

SpinWinningSymbol = _reflection.GeneratedProtocolMessageType('SpinWinningSymbol', (_message.Message,), dict(
  DESCRIPTOR = _SPINWINNINGSYMBOL,
  __module__ = 'Spin_pb2'
  # @@protoc_insertion_point(class_scope:PSXAPI.Response1203978105.SpinWinningSymbol)
  ))
_sym_db.RegisterMessage(SpinWinningSymbol)


# @@protoc_insertion_point(module_scope)
