# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Time.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import bcl_pb2 as bcl__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Time.proto',
  package='PSXAPI.Response81',
  syntax='proto2',
  serialized_pb=_b('\n\nTime.proto\x12\x11PSXAPI.Response81\x1a\tbcl.proto\"\x96\x02\n\x04Time\x12$\n\rServerTimeUtc\x18\x01 \x01(\x0b\x32\r.bcl.DateTime\x12\x1f\n\x08GameTime\x18\x02 \x01(\x0b\x32\r.bcl.TimeSpan\x12;\n\x0bGameDayTime\x18\x03 \x01(\x0e\x32\x1e.PSXAPI.Response81.GameDayTime:\x06Unset0\x12\x39\n\nGameSeason\x18\x04 \x01(\x0e\x32\x1d.PSXAPI.Response81.GameSeason:\x06Unset1\x12\x15\n\nTimeFactor\x18\x05 \x01(\x01:\x01\x30\x12\x38\n\x07Weather\x18\x06 \x01(\x0e\x32\x1f.PSXAPI.Response81.WeatherState:\x06Normal*G\n\x0bGameDayTime\x12\n\n\x06Unset0\x10\x00\x12\x0b\n\x07Morning\x10\x01\x12\x07\n\x03\x44\x61y\x10\x02\x12\x0b\n\x07\x45vening\x10\x03\x12\t\n\x05Night\x10\x04*H\n\nGameSeason\x12\n\n\x06Unset1\x10\x00\x12\n\n\x06Spring\x10\x01\x12\n\n\x06Summer\x10\x02\x12\n\n\x06\x41utumn\x10\x03\x12\n\n\x06Winter\x10\x04*.\n\x0cWeatherState\x12\n\n\x06Normal\x10\x00\x12\x08\n\x04Rain\x10\x01\x12\x08\n\x04Snow\x10\x02')
  ,
  dependencies=[bcl__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_GAMEDAYTIME = _descriptor.EnumDescriptor(
  name='GameDayTime',
  full_name='PSXAPI.Response81.GameDayTime',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Unset0', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Morning', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Day', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Evening', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Night', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=325,
  serialized_end=396,
)
_sym_db.RegisterEnumDescriptor(_GAMEDAYTIME)

GameDayTime = enum_type_wrapper.EnumTypeWrapper(_GAMEDAYTIME)
_GAMESEASON = _descriptor.EnumDescriptor(
  name='GameSeason',
  full_name='PSXAPI.Response81.GameSeason',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Unset1', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Spring', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Summer', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Autumn', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Winter', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=398,
  serialized_end=470,
)
_sym_db.RegisterEnumDescriptor(_GAMESEASON)

GameSeason = enum_type_wrapper.EnumTypeWrapper(_GAMESEASON)
_WEATHERSTATE = _descriptor.EnumDescriptor(
  name='WeatherState',
  full_name='PSXAPI.Response81.WeatherState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Normal', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Rain', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Snow', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=472,
  serialized_end=518,
)
_sym_db.RegisterEnumDescriptor(_WEATHERSTATE)

WeatherState = enum_type_wrapper.EnumTypeWrapper(_WEATHERSTATE)
Unset0 = 0
Morning = 1
Day = 2
Evening = 3
Night = 4
Unset1 = 0
Spring = 1
Summer = 2
Autumn = 3
Winter = 4
Normal = 0
Rain = 1
Snow = 2



_TIME = _descriptor.Descriptor(
  name='Time',
  full_name='PSXAPI.Response81.Time',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ServerTimeUtc', full_name='PSXAPI.Response81.Time.ServerTimeUtc', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GameTime', full_name='PSXAPI.Response81.Time.GameTime', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GameDayTime', full_name='PSXAPI.Response81.Time.GameDayTime', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GameSeason', full_name='PSXAPI.Response81.Time.GameSeason', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TimeFactor', full_name='PSXAPI.Response81.Time.TimeFactor', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Weather', full_name='PSXAPI.Response81.Time.Weather', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=323,
)

_TIME.fields_by_name['ServerTimeUtc'].message_type = bcl__pb2._DATETIME
_TIME.fields_by_name['GameTime'].message_type = bcl__pb2._TIMESPAN
_TIME.fields_by_name['GameDayTime'].enum_type = _GAMEDAYTIME
_TIME.fields_by_name['GameSeason'].enum_type = _GAMESEASON
_TIME.fields_by_name['Weather'].enum_type = _WEATHERSTATE
DESCRIPTOR.message_types_by_name['Time'] = _TIME
DESCRIPTOR.enum_types_by_name['GameDayTime'] = _GAMEDAYTIME
DESCRIPTOR.enum_types_by_name['GameSeason'] = _GAMESEASON
DESCRIPTOR.enum_types_by_name['WeatherState'] = _WEATHERSTATE

Time = _reflection.GeneratedProtocolMessageType('Time', (_message.Message,), dict(
  DESCRIPTOR = _TIME,
  __module__ = 'Time_pb2'
  # @@protoc_insertion_point(class_scope:PSXAPI.Response81.Time)
  ))
_sym_db.RegisterMessage(Time)


# @@protoc_insertion_point(module_scope)
