# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RenameMap.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RenameMap.proto',
  package='MAPAPI.Request2088766862',
  syntax='proto2',
  serialized_pb=_b('\n\x0fRenameMap.proto\x12\x18MAPAPI.Request2088766862\"3\n\tRenameMap\x12\x13\n\x0bMapNameFrom\x18\x01 \x01(\t\x12\x11\n\tMapNameTo\x18\x02 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RENAMEMAP = _descriptor.Descriptor(
  name='RenameMap',
  full_name='MAPAPI.Request2088766862.RenameMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MapNameFrom', full_name='MAPAPI.Request2088766862.RenameMap.MapNameFrom', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MapNameTo', full_name='MAPAPI.Request2088766862.RenameMap.MapNameTo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=96,
)

DESCRIPTOR.message_types_by_name['RenameMap'] = _RENAMEMAP

RenameMap = _reflection.GeneratedProtocolMessageType('RenameMap', (_message.Message,), dict(
  DESCRIPTOR = _RENAMEMAP,
  __module__ = 'RenameMap_pb2'
  # @@protoc_insertion_point(class_scope:MAPAPI.Request2088766862.RenameMap)
  ))
_sym_db.RegisterMessage(RenameMap)


# @@protoc_insertion_point(module_scope)
