# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game/response/payload/FlyUserData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='game/response/payload/FlyUserData.proto',
  package='PSXAPI.Response.Payload1349829419',
  syntax='proto2',
  serialized_pb=_b('\n\'game/response/payload/FlyUserData.proto\x12!PSXAPI.Response.Payload1349829419\"\xeb\x02\n\x0b\x46lyUserData\x12\x13\n\x08\x46lyMount\x18\x01 \x01(\x05:\x01\x30\x12\x13\n\x04\x41way\x18\x02 \x01(\x08:\x05\x66\x61lse\x12\x15\n\x06\x42\x61ttle\x18\x03 \x01(\x08:\x05\x66\x61lse\x12\x66\n\nMemberRank\x18\x04 \x01(\x0e\x32G.PSXAPI.Response.Payload1349829419.PREFIX_AGDFASBV2082223023.MemberRank:\tNoneValue\x12\x63\n\tStaffRank\x18\x05 \x01(\x0e\x32\x45.PSXAPI.Response.Payload1349829419.PREFIX_AGDFASBV409184260.StaffRank:\tNoneValue\x12\x11\n\tGuildName\x18\x06 \x01(\t\x12\x13\n\x08\x45mblemId\x18\x07 \x01(\r:\x01\x30\x12\x10\n\x05Level\x18\x08 \x01(\r:\x01\x30\x12\x14\n\x05Lobby\x18\t \x01(\x08:\x05\x66\x61lse\"D\n\x19PREFIX_AGDFASBV2082223023\"\'\n\nMemberRank\x12\r\n\tNoneValue\x10\x00\x12\n\n\x06Member\x10\x01\"g\n\x18PREFIX_AGDFASBV409184260\"K\n\tStaffRank\x12\r\n\tNoneValue\x10\x00\x12\r\n\tDeveloper\x10\x01\x12\x11\n\rGameModerator\x10\x02\x12\r\n\tModerator\x10\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PREFIX_AGDFASBV2082223023_MEMBERRANK = _descriptor.EnumDescriptor(
  name='MemberRank',
  full_name='PSXAPI.Response.Payload1349829419.PREFIX_AGDFASBV2082223023.MemberRank',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NoneValue', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Member', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=473,
  serialized_end=512,
)
_sym_db.RegisterEnumDescriptor(_PREFIX_AGDFASBV2082223023_MEMBERRANK)

_PREFIX_AGDFASBV409184260_STAFFRANK = _descriptor.EnumDescriptor(
  name='StaffRank',
  full_name='PSXAPI.Response.Payload1349829419.PREFIX_AGDFASBV409184260.StaffRank',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NoneValue', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Developer', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GameModerator', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Moderator', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=542,
  serialized_end=617,
)
_sym_db.RegisterEnumDescriptor(_PREFIX_AGDFASBV409184260_STAFFRANK)


_FLYUSERDATA = _descriptor.Descriptor(
  name='FlyUserData',
  full_name='PSXAPI.Response.Payload1349829419.FlyUserData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='FlyMount', full_name='PSXAPI.Response.Payload1349829419.FlyUserData.FlyMount', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Away', full_name='PSXAPI.Response.Payload1349829419.FlyUserData.Away', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Battle', full_name='PSXAPI.Response.Payload1349829419.FlyUserData.Battle', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MemberRank', full_name='PSXAPI.Response.Payload1349829419.FlyUserData.MemberRank', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='StaffRank', full_name='PSXAPI.Response.Payload1349829419.FlyUserData.StaffRank', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GuildName', full_name='PSXAPI.Response.Payload1349829419.FlyUserData.GuildName', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='EmblemId', full_name='PSXAPI.Response.Payload1349829419.FlyUserData.EmblemId', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Level', full_name='PSXAPI.Response.Payload1349829419.FlyUserData.Level', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Lobby', full_name='PSXAPI.Response.Payload1349829419.FlyUserData.Lobby', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=442,
)


_PREFIX_AGDFASBV2082223023 = _descriptor.Descriptor(
  name='PREFIX_AGDFASBV2082223023',
  full_name='PSXAPI.Response.Payload1349829419.PREFIX_AGDFASBV2082223023',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PREFIX_AGDFASBV2082223023_MEMBERRANK,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=444,
  serialized_end=512,
)


_PREFIX_AGDFASBV409184260 = _descriptor.Descriptor(
  name='PREFIX_AGDFASBV409184260',
  full_name='PSXAPI.Response.Payload1349829419.PREFIX_AGDFASBV409184260',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PREFIX_AGDFASBV409184260_STAFFRANK,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=514,
  serialized_end=617,
)

_FLYUSERDATA.fields_by_name['MemberRank'].enum_type = _PREFIX_AGDFASBV2082223023_MEMBERRANK
_FLYUSERDATA.fields_by_name['StaffRank'].enum_type = _PREFIX_AGDFASBV409184260_STAFFRANK
_PREFIX_AGDFASBV2082223023_MEMBERRANK.containing_type = _PREFIX_AGDFASBV2082223023
_PREFIX_AGDFASBV409184260_STAFFRANK.containing_type = _PREFIX_AGDFASBV409184260
DESCRIPTOR.message_types_by_name['FlyUserData'] = _FLYUSERDATA
DESCRIPTOR.message_types_by_name['PREFIX_AGDFASBV2082223023'] = _PREFIX_AGDFASBV2082223023
DESCRIPTOR.message_types_by_name['PREFIX_AGDFASBV409184260'] = _PREFIX_AGDFASBV409184260

FlyUserData = _reflection.GeneratedProtocolMessageType('FlyUserData', (_message.Message,), dict(
  DESCRIPTOR = _FLYUSERDATA,
  __module__ = 'game.response.payload.FlyUserData_pb2'
  # @@protoc_insertion_point(class_scope:PSXAPI.Response.Payload1349829419.FlyUserData)
  ))
_sym_db.RegisterMessage(FlyUserData)

PREFIX_AGDFASBV2082223023 = _reflection.GeneratedProtocolMessageType('PREFIX_AGDFASBV2082223023', (_message.Message,), dict(
  DESCRIPTOR = _PREFIX_AGDFASBV2082223023,
  __module__ = 'game.response.payload.FlyUserData_pb2'
  # @@protoc_insertion_point(class_scope:PSXAPI.Response.Payload1349829419.PREFIX_AGDFASBV2082223023)
  ))
_sym_db.RegisterMessage(PREFIX_AGDFASBV2082223023)

PREFIX_AGDFASBV409184260 = _reflection.GeneratedProtocolMessageType('PREFIX_AGDFASBV409184260', (_message.Message,), dict(
  DESCRIPTOR = _PREFIX_AGDFASBV409184260,
  __module__ = 'game.response.payload.FlyUserData_pb2'
  # @@protoc_insertion_point(class_scope:PSXAPI.Response.Payload1349829419.PREFIX_AGDFASBV409184260)
  ))
_sym_db.RegisterMessage(PREFIX_AGDFASBV409184260)


# @@protoc_insertion_point(module_scope)
